# Generated by Django 4.2.1 on 2023-05-15 17:25

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('black', models.BooleanField(default=False, help_text='0=default, 1=Black')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
