# Generated by Django 4.2.1 on 2023-05-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_size',
        ),
    ]
